# 1 "data/maps/BattleFrontier_RankingHall/scripts.pory"

# 2 "data/maps/BattleFrontier_RankingHall/scripts.pory"
BattleFrontier_RankingHall_MapScripts::
# 3 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	.byte 0
# 4 "data/maps/BattleFrontier_RankingHall/scripts.pory"

# 5 "data/maps/BattleFrontier_RankingHall/scripts.pory"
BattleFrontier_RankingHall_EventScript_TowerSinglesRecords::
# 6 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	lockall
# 7 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	setvar VAR_0x8005, RANKING_HALL_TOWER_SINGLES
# 8 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	goto BattleFrontier_RankingHall_EventScript_ShowRecords
# 9 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	end
# 10 "data/maps/BattleFrontier_RankingHall/scripts.pory"

# 11 "data/maps/BattleFrontier_RankingHall/scripts.pory"
BattleFrontier_RankingHall_EventScript_TowerDoublesRecords::
# 12 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	lockall
# 13 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	setvar VAR_0x8005, RANKING_HALL_TOWER_DOUBLES
# 14 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	goto BattleFrontier_RankingHall_EventScript_ShowRecords
# 15 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	end
# 16 "data/maps/BattleFrontier_RankingHall/scripts.pory"

# 17 "data/maps/BattleFrontier_RankingHall/scripts.pory"
BattleFrontier_RankingHall_EventScript_TowerMultisRecords::
# 18 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	lockall
# 19 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	setvar VAR_0x8005, RANKING_HALL_TOWER_MULTIS
# 20 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	goto BattleFrontier_RankingHall_EventScript_ShowRecords
# 21 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	end
# 22 "data/maps/BattleFrontier_RankingHall/scripts.pory"

# 23 "data/maps/BattleFrontier_RankingHall/scripts.pory"
BattleFrontier_RankingHall_EventScript_TowerLinkRecords::
# 24 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	lockall
# 25 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	setvar VAR_0x8005, RANKING_HALL_TOWER_LINK
# 26 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	goto BattleFrontier_RankingHall_EventScript_ShowRecords
# 27 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	end
# 28 "data/maps/BattleFrontier_RankingHall/scripts.pory"

# 29 "data/maps/BattleFrontier_RankingHall/scripts.pory"
BattleFrontier_RankingHall_EventScript_ArenaRecords::
# 30 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	lockall
# 31 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	setvar VAR_0x8005, RANKING_HALL_ARENA
# 32 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	goto BattleFrontier_RankingHall_EventScript_ShowRecords
# 33 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	end
# 34 "data/maps/BattleFrontier_RankingHall/scripts.pory"

# 35 "data/maps/BattleFrontier_RankingHall/scripts.pory"
BattleFrontier_RankingHall_EventScript_PalaceRecords::
# 36 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	lockall
# 37 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	setvar VAR_0x8005, RANKING_HALL_PALACE
# 38 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	goto BattleFrontier_RankingHall_EventScript_ShowRecords
# 39 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	end
# 40 "data/maps/BattleFrontier_RankingHall/scripts.pory"

# 41 "data/maps/BattleFrontier_RankingHall/scripts.pory"
BattleFrontier_RankingHall_EventScript_FactoryRecords::
# 42 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	lockall
# 43 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	setvar VAR_0x8005, RANKING_HALL_FACTORY
# 44 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	goto BattleFrontier_RankingHall_EventScript_ShowRecords
# 45 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	end
# 46 "data/maps/BattleFrontier_RankingHall/scripts.pory"

# 47 "data/maps/BattleFrontier_RankingHall/scripts.pory"
BattleFrontier_RankingHall_EventScript_DomeRecords::
# 48 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	lockall
# 49 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	setvar VAR_0x8005, RANKING_HALL_DOME
# 50 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	goto BattleFrontier_RankingHall_EventScript_ShowRecords
# 51 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	end
# 52 "data/maps/BattleFrontier_RankingHall/scripts.pory"

# 53 "data/maps/BattleFrontier_RankingHall/scripts.pory"
BattleFrontier_RankingHall_EventScript_PikeRecords::
# 54 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	lockall
# 55 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	setvar VAR_0x8005, RANKING_HALL_PIKE
# 56 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	goto BattleFrontier_RankingHall_EventScript_ShowRecords
# 57 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	end
# 58 "data/maps/BattleFrontier_RankingHall/scripts.pory"

# 59 "data/maps/BattleFrontier_RankingHall/scripts.pory"
BattleFrontier_RankingHall_EventScript_PyramidRecords::
# 60 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	lockall
# 61 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	setvar VAR_0x8005, RANKING_HALL_PYRAMID
# 62 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	goto BattleFrontier_RankingHall_EventScript_ShowRecords
# 63 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	end
# 64 "data/maps/BattleFrontier_RankingHall/scripts.pory"

# 65 "data/maps/BattleFrontier_RankingHall/scripts.pory"
BattleFrontier_RankingHall_EventScript_ShowRecords::
# 66 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	special ShowRankingHallRecordsWindow
# 67 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	waitbuttonpress
# 68 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	special RemoveRecordsWindow
# 69 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	releaseall
# 70 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	end
# 71 "data/maps/BattleFrontier_RankingHall/scripts.pory"

# 72 "data/maps/BattleFrontier_RankingHall/scripts.pory"
BattleFrontier_RankingHall_EventScript_Attendant::
# 73 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	msgbox BattleFrontier_RankingHall_Text_ExplainRankingHall, MSGBOX_NPC
# 74 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	end
# 75 "data/maps/BattleFrontier_RankingHall/scripts.pory"

# 76 "data/maps/BattleFrontier_RankingHall/scripts.pory"
BattleFrontier_RankingHall_EventScript_DomePikeFactoryRecordsSign::
# 77 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	msgbox BattleFrontier_RankingHall_Text_DomePikeFactoryRecords, MSGBOX_SIGN
# 78 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	end
# 79 "data/maps/BattleFrontier_RankingHall/scripts.pory"

# 80 "data/maps/BattleFrontier_RankingHall/scripts.pory"
BattleFrontier_RankingHall_EventScript_PalaceArenaPyramidRecordsSIgn::
# 81 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	msgbox BattleFrontier_RankingHall_Text_PalaceArenaPyramidRecords, MSGBOX_SIGN
# 82 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	end
# 83 "data/maps/BattleFrontier_RankingHall/scripts.pory"

# 84 "data/maps/BattleFrontier_RankingHall/scripts.pory"
BattleFrontier_RankingHall_EventScript_NinjaBoy::
# 85 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	lock
# 86 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	faceplayer
# 87 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	msgbox BattleFrontier_RankingHall_Text_IsYourNameOnThisList, MSGBOX_YESNO
# 88 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	goto_if_eq VAR_RESULT, YES, BattleFrontier_RankingHall_EventScript_NinjaBoyNameOnList
# 89 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	msgbox BattleFrontier_RankingHall_Text_WorkHarderIfYouSawFriendsName, MSGBOX_DEFAULT
# 90 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	release
# 91 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	end
# 92 "data/maps/BattleFrontier_RankingHall/scripts.pory"

# 93 "data/maps/BattleFrontier_RankingHall/scripts.pory"
BattleFrontier_RankingHall_EventScript_NinjaBoyNameOnList::
# 94 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	msgbox BattleFrontier_RankingHall_Text_WowThatsSuper, MSGBOX_DEFAULT
# 95 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	release
# 96 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	end
# 97 "data/maps/BattleFrontier_RankingHall/scripts.pory"

# 98 "data/maps/BattleFrontier_RankingHall/scripts.pory"
BattleFrontier_RankingHall_EventScript_Boy::
# 99 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	msgbox BattleFrontier_RankingHall_Text_MyNamesNotUpThere, MSGBOX_NPC
# 100 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	end
# 101 "data/maps/BattleFrontier_RankingHall/scripts.pory"

# 102 "data/maps/BattleFrontier_RankingHall/scripts.pory"
BattleFrontier_RankingHall_Text_ExplainRankingHall:
# 103 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	.string "This is the RANKING HALL.\p"
# 104 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	.string "This is where we recognize the immortal\n"
# 105 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	.string "TRAINERS who left great records in\l"
# 106 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	.string "BATTLE FRONTIER events.$"
# 107 "data/maps/BattleFrontier_RankingHall/scripts.pory"

# 108 "data/maps/BattleFrontier_RankingHall/scripts.pory"
BattleFrontier_RankingHall_Text_DomePikeFactoryRecords:
# 109 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	.string "BATTLE DOME, BATTLE PIKE,\n"
# 110 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	.string "and BATTLE FACTORY Records$"
# 111 "data/maps/BattleFrontier_RankingHall/scripts.pory"

# 112 "data/maps/BattleFrontier_RankingHall/scripts.pory"
BattleFrontier_RankingHall_Text_PalaceArenaPyramidRecords:
# 113 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	.string "BATTLE PALACE, BATTLE ARENA,\n"
# 114 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	.string "and BATTLE PYRAMID Records$"
# 115 "data/maps/BattleFrontier_RankingHall/scripts.pory"

# 116 "data/maps/BattleFrontier_RankingHall/scripts.pory"
BattleFrontier_RankingHall_Text_IsYourNameOnThisList:
# 117 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	.string "Hi, is your name on this list?$"
# 118 "data/maps/BattleFrontier_RankingHall/scripts.pory"

# 119 "data/maps/BattleFrontier_RankingHall/scripts.pory"
BattleFrontier_RankingHall_Text_WowThatsSuper:
# 120 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	.string "Wow, that's super!\n"
# 121 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	.string "I'll have to try harder, too!$"
# 122 "data/maps/BattleFrontier_RankingHall/scripts.pory"

# 123 "data/maps/BattleFrontier_RankingHall/scripts.pory"
BattleFrontier_RankingHall_Text_WorkHarderIfYouSawFriendsName:
# 124 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	.string "Oh, is that right?\p"
# 125 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	.string "If you saw your friend's name up here,\n"
# 126 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	.string "I bet it would make you work harder!$"
# 127 "data/maps/BattleFrontier_RankingHall/scripts.pory"

# 128 "data/maps/BattleFrontier_RankingHall/scripts.pory"
BattleFrontier_RankingHall_Text_MyNamesNotUpThere:
# 129 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	.string "Hmm…\n"
# 130 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	.string "My name's not up there…\p"
# 131 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	.string "Well, it's only natural since I haven't\n"
# 132 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	.string "taken any challenges yet.$"
